"""add visibility to project and business_role to member

Revision ID: 764b1f99dff0
Revises: documents_v1
Create Date: 2026-06-09 09:44:18.826875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # pyright: ignore[reportMissingImports]


# revision identifiers, used by Alembic.
revision: str = '764b1f99dff0'
down_revision: Union[str, Sequence[str], None] = 'documents_v1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('business_role', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('visibility', sa.String(length=50), nullable=True))
    op.drop_index(op.f('uix_project_substep_stakeholder'), table_name='stakeholders')
    op.create_unique_constraint('uix_project_substep_stakeholder', 'stakeholders', ['project_id', 'substep_id', 'name'])
    op.create_index(op.f('ix_stakeholders_substep_id'), 'stakeholders', ['substep_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stakeholders_substep_id'), table_name='stakeholders')
    op.drop_constraint('uix_project_substep_stakeholder', 'stakeholders', type_='unique')
    op.create_index(op.f('uix_project_substep_stakeholder'), 'stakeholders', ['project_id', 'substep_id', 'name'], unique=True)
    op.drop_column('projects', 'visibility')
    op.drop_column('project_members', 'business_role')
    # ### end Alembic commands ###
